name: preprod Worker
on:
  push:
    paths:
      - etc/cf-workers/preprod/preprod.js

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'etc/cf-workers/preprod/'